basePath: /api
definitions:
  common.ErrResponse:
    properties:
      msg:
        type: string
    type: object
  uploader.PresignedDownload:
    properties:
      url:
        type: string
    type: object
  uploader.PresignedUpload:
    properties:
      object_key:
        type: string
      url:
        type: string
    type: object
  uploader.UploadedFilePresenter:
    properties:
      name:
        type: string
      url:
        type: string
    type: object
  uploader.UploadedFilesPresenter:
    properties:
      uploaded_files:
        items:
          $ref: '#/definitions/uploader.UploadedFilePresenter'
        type: array
    type: object
info:
  contact:
    email: minghsu0107@gmail.com
    name: Ming Hsu
  description: Uploader service API
  title: Uploader Service Swagger API
  version: "2.0"
paths:
  /uploader/download/presigned:
    get:
      description: Get presigned url for downloading a file from S3
      parameters:
      - description: object key
        in: query
        name: object_key
        required: true
        type: string
      - description: channel authorization
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/uploader.PresignedDownload'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/common.ErrResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/common.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/common.ErrResponse'
      summary: Get presigned download url
      tags:
      - uploader
  /uploader/upload/files:
    post:
      consumes:
      - multipart/form-data
      description: Upload files to S3 bucket (deprecated; use presigned urls instead)
      parameters:
      - collectionFormat: multi
        description: files to upload
        in: formData
        items:
          type: file
        name: files
        required: true
        type: array
      - description: channel authorization
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/uploader.UploadedFilesPresenter'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/common.ErrResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/common.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/common.ErrResponse'
      summary: Upload files (deprecated)
      tags:
      - uploader
  /uploader/upload/presigned:
    get:
      description: Get presigned url for uploading a file to S3
      parameters:
      - description: file extension
        in: query
        name: ext
        required: true
        type: string
      - description: channel authorization
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/uploader.PresignedUpload'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/common.ErrResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/common.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/common.ErrResponse'
      summary: Get presigned upload url
      tags:
      - uploader
swagger: "2.0"
